import type { Locale } from './i18n'

const ENGLISH_TAG_LABELS: Record<string, string> = {
  八股: 'Interview Notes',
  算法: 'Algorithms',
  算法竞赛: 'Competitive Programming',
  题解整理: 'Solutions',
  数论: 'Number Theory',
  数据结构: 'Data Structures',
  博弈论: 'Game Theory',
  图论: 'Graph Theory',
  持久化: 'Persistence',
  构造: 'Constructive',
  测试: 'Testing',
  组合数学: 'Combinatorics',
  缓存: 'Caching',
  语法: 'Syntax',
  锁: 'Locking',
  高可用: 'High Availability',
  事务: 'Transactions',
  二分: 'Binary Search',
  代码高亮: 'Code Highlighting',
  位运算: 'Bit Operations',
  入门: 'Basics',
  内存管理: 'Memory Management',
  出题: 'Problem Design',
  分布式锁: 'Distributed Locks',
  前缀和: 'Prefix Sums',
  反射: 'Reflection',
  同余: 'Congruences',
  多项式: 'Polynomials',
  字符串: 'Strings',
  并发: 'Concurrency',
  形式幂级数: 'Formal Power Series',
  思维转化: 'Thinking Shifts',
  思维题: 'Thinking Problems',
  思考: 'Thoughts',
  搜索: 'Search',
  操作系统: 'Operating Systems',
  欧几里得算法: 'Euclidean Algorithm',
  欧拉函数: 'Euler Totient',
  洛谷: 'Luogu',
  消息队列: 'Message Queues',
  牛客: 'Nowcoder',
  状态表示: 'State Representation',
  狄利克雷卷积: 'Dirichlet Convolution',
  生成函数: 'Generating Functions',
  积性函数: 'Multiplicative Functions',
  筛法: 'Sieve Methods',
  索引: 'Indexes',
  线性筛: 'Linear Sieve',
  线程: 'Threads',
  线程池: 'Thread Pools',
  莫比乌斯函数: 'Mobius Function',
  莫比乌斯反演: 'Mobius Inversion',
  计算机网络: 'Computer Networks',
  贪心: 'Greedy',
  进程: 'Processes',
  邀请赛: 'Invitational',
  集合: 'Collections',
  题目设计: 'Problem Design',
  b树: 'B-Trees',
  sg函数: 'SG Function'
}

export function getLocalizedTagLabel(tag: string, locale: Locale) {
  if (locale !== 'en') return tag
  return ENGLISH_TAG_LABELS[tag] ?? tag
}
